//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteControleClient.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannedProgramms
    {
        public int id { get; set; }
        public int Day_id { get; set; }
        public string ProgName { get; set; }
    
        public virtual DaysOfWeek DaysOfWeek { get; set; }
    }
}
